# Generated by Django 5.1.5 on 2025-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_category_item_checked_out_item_color_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('ACC', 'Accessories'), ('APP', 'Apparatus'), ('APA', 'Apparatus Accessories'), ('BAC', 'Backpacks'), ('BEL', 'Belts'), ('BOD', 'Bodysuits'), ('BOO', 'Bootyshorts'), ('BUS', 'Bustles'), ('CAP', 'Capes'), ('COR', 'Corset'), ('COS', 'Costumes'), ('CRO', 'Crowns'), ('CUM', 'Cumberbunds'), ('DEC', 'Decor'), ('DRE', 'Dresses'), ('ELE', 'Electronics'), ('GAR', 'Garden'), ('GLO', 'Gloves'), ('HAI', 'Hair Accessories'), ('HAL', 'Halloween Accessories'), ('HAT', 'Hats'), ('HEA', 'Headdresses'), ('JAC', 'Jackets'), ('JEW', 'Jewelry'), ('LED', 'LED'), ('LEG', 'Leggings'), ('MAS', 'Masks'), ('MIR', 'Mirror'), ('NEC', 'Necklaces'), ('PAD', 'Padding'), ('PAN', 'Pants'), ('PAS', 'Pantsuits'), ('PRO', 'Props'), ('RUF', 'Ruffles'), ('SHI', 'Shirts'), ('SHO', 'Shoes'), ('SHT', 'Shorts'), ('SHR', 'Shrugs'), ('SIG', 'Signage'), ('SKA', 'Skate Covers'), ('SKI', 'Skirts'), ('STE', 'Steampunk Accessories'), ('STI', 'Stilts'), ('STO', 'Stoles'), ('TAB', 'Table Skirts'), ('TIA', 'Tiaras'), ('TIE', 'Ties'), ('TIG', 'Tights'), ('TRA', 'Tracksuits'), ('TRY', 'Trays'), ('TUT', 'Tutus'), ('TWE', 'Twenties'), ('UNS', 'Undershirts'), ('UNT', 'Undertard'), ('UNI', 'Unitard'), ('VES', 'Vests'), ('WIG', 'Wigs'), ('MIS', 'Miscellaneous')], max_length=4),
        ),
    ]
