# Generated by Django 5.1.5 on 2025-05-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
