# Generated by Django 5.1.5 on 2025-11-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_checked_out_remove_item_in_repair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
