# Generated by Django 5.1.5 on 2025-11-02 20:43

from django.db import migrations
from django.contrib.auth.models import Group

def create_default_groups(apps, schema_editor):
    groups = ['Manager', 'Staff']
    for group_name in groups:
        Group.objects.get_or_create(name=group_name)

def delete_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Manager', 'Staff']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),  # latest auth migration
    ]

    operations = [
        migrations.RunPython(create_default_groups, delete_default_groups),
    ]
